# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/generated-mne-for-eeg',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/generated-mne-for-eeg',
                'lib_path': 'generated_mne_for_eeg'},
  'syms': {'generated_mne_for_eeg.core': {'generated_mne_for_eeg.core.foo': ('core.html#foo', 'generated_mne_for_eeg/core.py')}}}
